version: '3'

vars:
  mac_bin: bin/splitter

tasks:
  test:
    dir: src
    cmds:
      - go test ./...
  build-mac:
    dir: src
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -o ../{{.mac_bin}} main.go
  install:
    deps:
      - build-mac
    cmds:
      - mv {{.mac_bin}} /usr/local/bin/splitter